server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://group7:7APEuj1JSV9aJwls@cluster0.dj4xd.mongodb.net/ClientsService?retryWrites=true&w=majority
      database: ClientsService

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
            
resilience4j.circuitbreaker:
  instances:
    productsCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10